// Code generated by protoc-gen-go-ttrpc. DO NOT EDIT.
// source: github.com/containerd/containerd/api/events/image.proto
package events

import (
	context "context"
	ttrpc "github.com/containerd/ttrpc"
)
